# Generated by Django 3.2.9 on 2021-12-02 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0002_alter_destination_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Destination',
            new_name='Destinations',
        ),
    ]
